//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRM.Logic.PerformanceTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRM.Logic.PerformanceTests.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vhigh,vhigh,2,2,small,low,unacc
        ///vhigh,vhigh,2,2,small,med,unacc
        ///vhigh,vhigh,2,2,small,high,unacc
        ///vhigh,vhigh,2,2,med,low,unacc
        ///vhigh,vhigh,2,2,med,med,unacc
        ///vhigh,vhigh,2,2,med,high,unacc
        ///vhigh,vhigh,2,2,big,low,unacc
        ///vhigh,vhigh,2,2,big,med,unacc
        ///vhigh,vhigh,2,2,big,high,unacc
        ///vhigh,vhigh,2,4,small,low,unacc
        ///vhigh,vhigh,2,4,small,med,unacc
        ///vhigh,vhigh,2,4,small,high,unacc
        ///vhigh,vhigh,2,4,med,low,unacc
        ///vhigh,vhigh,2,4,med,med,unacc
        ///vhigh,vhigh,2,4,med,high,unacc
        ///vhigh,vhigh,2,4,big,low,unacc        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string car_100k {
            get {
                return ResourceManager.GetString("car_100k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p,x,s,n,t,p,f,c,n,k,e,e,s,s,w,w,p,w,o,p,k,s,u
        ///e,x,s,y,t,a,f,c,b,k,e,c,s,s,w,w,p,w,o,p,n,n,g
        ///e,b,s,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,n,m
        ///p,x,y,w,t,p,f,c,n,n,e,e,s,s,w,w,p,w,o,p,k,s,u
        ///e,x,s,g,f,n,f,w,b,k,t,e,s,s,w,w,p,w,o,e,n,a,g
        ///e,x,y,y,t,a,f,c,b,n,e,c,s,s,w,w,p,w,o,p,k,n,g
        ///e,b,s,w,t,a,f,c,b,g,e,c,s,s,w,w,p,w,o,p,k,n,m
        ///e,b,y,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,s,m
        ///p,x,y,w,t,p,f,c,n,p,e,e,s,s,w,w,p,w,o,p,k,v,g
        ///e,b,s,y,t,a,f,c,b,g,e,c,s,s,w,w,p,w,o,p,k,s,m
        ///e,x,y,y,t,l,f,c,b,g,e,c,s,s,w,w,p,w,o,p,n, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mushrooms {
            get {
                return ResourceManager.GetString("mushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p,x,s,n,t,p,f,c,n,k,e,e,s,s,w,w,p,w,o,p,k,s,u
        ///e,x,s,y,t,a,f,c,b,k,e,c,s,s,w,w,p,w,o,p,n,n,g
        ///e,b,s,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,n,m
        ///p,x,y,w,t,p,f,c,n,n,e,e,s,s,w,w,p,w,o,p,k,s,u
        ///e,x,s,g,f,n,f,w,b,k,t,e,s,s,w,w,p,w,o,e,n,a,g
        ///e,x,y,y,t,a,f,c,b,n,e,c,s,s,w,w,p,w,o,p,k,n,g
        ///e,b,s,w,t,a,f,c,b,g,e,c,s,s,w,w,p,w,o,p,k,n,m
        ///e,b,y,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,s,m
        ///p,x,y,w,t,p,f,c,n,p,e,e,s,s,w,w,p,w,o,p,k,v,g
        ///e,b,s,y,t,a,f,c,b,g,e,c,s,s,w,w,p,w,o,p,k,s,m
        ///e,x,y,y,t,l,f,c,b,g,e,c,s,s,w,w,p,w,o,p,n, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mushrooms_small {
            get {
                return ResourceManager.GetString("mushrooms_small", resourceCulture);
            }
        }
    }
}
